// <auto-generated />
using System;
using Aiko_Hastanesi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aiko_Hastanesi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241211100459_Musaitlik")]
    partial class Musaitlik
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aiko_Hastanesi.Models.Acil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcilTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OluşturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BolumId");

                    b.ToTable("Acils");
                });

            modelBuilder.Entity("Aiko_Hastanesi.Models.Asistan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Asistans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Ali Yılmaz",
                            Adres = "İstanbul, Türkiye",
                            Email = "ali.yilmaz@example.com",
                            Telefon = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            AdSoyad = "Ayşe Demir",
                            Adres = "Ankara, Türkiye",
                            Email = "ayse.demir@example.com",
                            Telefon = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            AdSoyad = "Mehmet Can",
                            Adres = "İzmir, Türkiye",
                            Email = "mehmet.can@example.com",
                            Telefon = "5551234567"
                        },
                        new
                        {
                            Id = 4,
                            AdSoyad = "Fatma Korkmaz",
                            Adres = "Bursa, Türkiye",
                            Email = "fatma.korkmaz@example.com",
                            Telefon = "4445678901"
                        });
                });

            modelBuilder.Entity("Aiko_Hastanesi.Models.Bolum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HocaId")
                        .HasColumnType("int");

                    b.Property<int>("YatakSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HocaId");

                    b.ToTable("Bolums");
                });

            modelBuilder.Entity("Aiko_Hastanesi.Models.Hoca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Hocas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Ali Yılmaz",
                            Adres = "İstanbul, Türkiye",
                            Email = "ali.yilmaz@example.com",
                            Telefon = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            AdSoyad = "Ayşe Demir",
                            Adres = "Ankara, Türkiye",
                            Email = "ayse.demir@example.com",
                            Telefon = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            AdSoyad = "Mehmet Can",
                            Adres = "İzmir, Türkiye",
                            Email = "mehmet.can@example.com",
                            Telefon = "5551234567"
                        },
                        new
                        {
                            Id = 4,
                            AdSoyad = "Fatma Korkmaz",
                            Adres = "Bursa, Türkiye",
                            Email = "fatma.korkmaz@example.com",
                            Telefon = "4445678901"
                        });
                });

            modelBuilder.Entity("Aiko_Hastanesi.Models.HocaMusaitlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicSaati")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisSaati")
                        .HasColumnType("datetime2");

                    b.Property<int>("HocaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HocaID");

                    b.ToTable("HocaMusaitliks");
                });

            modelBuilder.Entity("Aiko_Hastanesi.Models.Nobet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsistanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslangicSaati")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisSaati")
                        .HasColumnType("datetime2");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AsistanID");

                    b.HasIndex("BolumID");

                    b.ToTable("Nobets");
                });

            modelBuilder.Entity("Aiko_Hastanesi.Models.Acil", b =>
                {
                    b.HasOne("Aiko_Hastanesi.Models.Bolum", "Bolum")
                        .WithMany()
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("Aiko_Hastanesi.Models.Bolum", b =>
                {
                    b.HasOne("Aiko_Hastanesi.Models.Hoca", "Hoca")
                        .WithMany()
                        .HasForeignKey("HocaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hoca");
                });

            modelBuilder.Entity("Aiko_Hastanesi.Models.HocaMusaitlik", b =>
                {
                    b.HasOne("Aiko_Hastanesi.Models.Hoca", "Hoca")
                        .WithMany()
                        .HasForeignKey("HocaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hoca");
                });

            modelBuilder.Entity("Aiko_Hastanesi.Models.Nobet", b =>
                {
                    b.HasOne("Aiko_Hastanesi.Models.Asistan", "Asistan")
                        .WithMany()
                        .HasForeignKey("AsistanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aiko_Hastanesi.Models.Bolum", "Bolum")
                        .WithMany()
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asistan");

                    b.Navigation("Bolum");
                });
#pragma warning restore 612, 618
        }
    }
}
